### ISSUE TITLE
Ice core example

### ISSUE THREAD

**Issue by scroobiustrip** [sagar87/numgp#1]
Hi there,

Thanks for the great library, it was exactly what I was looking for! I am attempting to port the [Mauna Lao CO2](https://www.pymc.io/projects/examples/en/latest/gaussian_processes/GP-MaunaLoa2.html) model ([example notebook here](https://colab.research.google.com/drive/1QJLt0bLC_gRoym8DK6OHNKD5CFr0t-wB?usp=sharing)) but was running into difficulties when using the predict method, the model is basically.

```python
def model(X, y, Xnew):

    T = X.shape[0]

    η = numpyro.sample('η', dist.HalfNormal(5))
    ℓ = numpyro.sample('ℓ', dist.Gamma(4, 2))
    α = numpyro.sample('α', dist.Gamma(3, 1))  
    cov = η**2 * npg.cov.RatQuad(1, α, ℓ)

    gp = npg.gp.Marginal('f', cov_func=cov)

    t_diff = numpyro.sample('t_diff', dist.Normal(0., 0.02), sample_shape=(T,))
    t_uncert = X - t_diff

    σ = numpyro.sample('σ', dist.HalfNormal(5))
    
    y_ = gp.marginal_likelihood(X=t_uncert[:, None], y=y, noise=σ)
    
    _ = gp.conditional(t_uncert[:, None], Xnew)
```

Train methods:

```python
svi = SVIHandler(model, AutoDiagonalNormal(model), num_epochs=10000)
svi.fit(t_n, y_train, None, True, return_sites=('ℓ', 'η', 'α', 'σ', 'f'))
```

Predict methods:

```python
Xnew = np.linspace(-100, 2150, 2000) * 0.01

marg = MarginalConditional(model, 'f')
mu, var = marg.conditional_from_guide(
    svi.guide, 
    svi.params, 
    X,
    y_train, 
    Xnew[:, None]
)
```

However, when it comes to make predictions based on the new data, it only returns `nan` is there something I'm missing?

```python
 with numpyro.handlers.seed(rng_seed=34):
    pred = numpyro.sample('pred', dist.MultivariateNormal(loc=mu, covariance_matrix=var).expand([200]))
```

```python
pred
>>> Array([[nan, nan, nan, ..., nan, nan, nan],
           [nan, nan, nan, ..., nan, nan, nan],
           [nan, nan, nan, ..., nan, nan, nan],
           ...,
           [nan, nan, nan, ..., nan, nan, nan],
           [nan, nan, nan, ..., nan, nan, nan],
           [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)
```

**Comment by sagar87** [comment]
Hi [scroobiustrip](https://github.com/scroobiustrip)

Sorry for the late reply, this somehow slipped through. To be honest, I do not understand why these numerical issues arise in JAX/torch but not in PyMC3's theano backend. Setting default float type to 64 bit helps sometimes, but makes inference painfully slow. Would be interesting to find out why this is the case ...

**Comment by scroobiustrip** [comment]
Hey no worries! I'm happy to report that everything in fact works exactly as expected and where I was going wrong was with the passing in of the `t_diff` variable which seemed to be the cause of the numerical instability. Thanks once again for the package, it's been a great help recently.
